// Vulnerability Ids

const vulnerabilitiesX = {
  AUTH_THROUGH_TX_ORIGIN: 'AUTH_THROUGH_TX_ORIGIN',
  FLOATING_PRAGMA: 'FLOATING_PRAGMA',
  HARDCODED_GAS_AMOUNT: 'HARDCODED_GAS_AMOUNT',
  INT_OVERFLOW: 'INT_OVERFLOW',
  INT_UNDERFLOW: 'INT_UNDERFLOW',
  OUTDATED_COMPILER_VERSION: 'OUTDATED_COMPILER_VERSION',
  REENTRANCY: 'SWC-107',
  UNCHECKED_CALL_RETURN_VALUE: 'UNCHECKED_CALL_RETURN_VALUE'
}

const vulnerabilities = {
  AUTH_THROUGH_TX_ORIGIN: 'SWC-115', 
  FLOATING_PRAGMA: 'SWC-103',           
  HARDCODED_GAS_AMOUNT: 'SWC-132',      
  INT_OVERFLOW: 'SWC-101',              
  INT_UNDERFLOW: 'SWC-101',             
  OUTDATED_COMPILER_VERSION: 'SWC-103', 
  REENTRANCY: 'SWC-107',                
  UNCHECKED_CALL_RETURN_VALUE: 'SWC-104' 
};



module.exports = { vulnerabilities }
